### ISSUE TITLE
Sleep statement

### ISSUE THREAD

**Issue by maberer** [rivo/users#1]
I found sleep statements in the code - is there a reason for them?

https://github.com/rivo/users/blob/master/loginout.go#L38
https://github.com/rivo/users/blob/master/signup.go#L143

**Comment by rivo** [comment]
Thanks for the question.

I added those to limit brute force attacks. My thinking was that with a second delay, an attacker will only be able to test 60 passwords max (or verification links) a minute.

Now I realize that a `Sleep()` statement doesn't reduce the number of requests processed by the server. So this will need a bit more sophistication.

Let me think about this.

**Comment by maberer** [comment]
Ah ok I see. Well the server would just create a new goroutine I guess... 

Sorry accidentally closed the issue.

**Comment by rivo** [comment]
Yes, it would. I didn't think of that.

I'll find a solution and add it to the package.

**Comment by rivo** [comment]
I wrapped the `Sleep()` statements in mutexes now so they actually have an effect.

**Comment by maberer** [comment]
Thank you - I looked at the changes... I hope you do not mind if I comment on them...

[https://github.com/rivo/users/blob/master/signup.go#L143](pauseMutex.Lock())
--> While easy and certainly effective in one way.... doesn't this block all concurrent verify requests since the mutex is not related to a certain identifier....? The user is fetched a few lines further down so wouldn't it be possible to create a mutex map here as well? In case of concurrent requests, the current implementation locks out requests for up to a few seconds since all requests stack up in front of the mutex (getting even worse with higher concurrency)... please correct me if I am wrong...

[https://github.com/rivo/users/blob/master/loginout.go#L39](userMutexesMutex.Lock())
--> Here, the mutex is created on a per email basis... so the request is throttled on an account basis... that's fine. Nevertheless, the map grows larger and larger until it hits its maximum length of 100k elements... because email address strings are used as keys, this map requires quite a bit of memory.... additionally, keys older than x could be wiped periodically... I guess... but in its current implementation, the map only grows.

I thought about the throttle concept as well... and I think it is a challenge to implement a one-fits all solution here... Wouldn't it be possible, to create a function in the config struct that allows users to implement their own rate-limiter if required? As a default, the current implementation or a "no-operation" function could be used -  further, it would allow people to overwrite the implementation with a custom solution. That would extend the already great extensibility of this library provided by the config struct... 

I found quite a lot of already-made rate-limiting implementations, so I think it should not be too hard for users to attach their own if required. 

a few examples:
https://github.com/golang/go/wiki/RateLimiting
https://github.com/uber-go/ratelimit

**Comment by maberer** [comment]
It could probably look like the following...  as a first attempt

```
var Config = struct { 
    // existing Config content

   // ThrottleVerification throttles verification attempts based on a user id
   ThrottleVerification func(userID string) ()

   // ThrottleLogin throttles login attempts based on an accounts email address
   ThrottleLogin func(email string) ()

} {
   ThrottleVerification: func(userID User)  {
           //noop or current implmementation
   },
    ThrottleLogin: func(email string) {
         //noop or current implmementation
    }
}
```

**Comment by rivo** [comment]
I committed a change that implements your suggestion.

However, for the verification part, it doesn't work the way you suggest. The idea here is to make it harder for attackers to guess a valid verification ID. If I need to know the user ID for the throttle function, then it will only be called once the user is known, that is, when the attacker has found a hit. That would make the mechanism basically useless. I tried thinking of other ways to partition the throttling (e.g. IP address, browser agent) but in reality, there's no effective way that can't be circumvented.

I also don't see a major problem in blocking the `Verify()` function globally. Unless you have multiple signups per second, it probably won't be noticeable. (And if you do, maybe this package is probably not sufficient overall anyway.)

For the login throttling, I reduced the maximum map size of the default implementation. Email addresses can be max. 320 characters long so on a reasonably large server, I didn't see a major problem with the map's size but I reduced it anyway. I realize one could implement something more sophisticated, where entries expire after some time or a FIFO store but I don't really think it's worth it in this case.

Anyway, now you can choose yourself how you want this to work.
