### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by frederikhors** [rivo/users#10]
Is this abandoned?

**Comment by rivo** [comment]
Kind of depends on interest in this project. I wouldn't say it's abandoned but issues may take a while to process as the little time I have usually goes into [`rivo/tview`](https://github.com/rivo/tview). New features, especially larger ones, will be difficult to take care of. (Larger) PRs also take a lot of time as I then have to review code.

But I'm always interested in fixing bugs. If you find something that needs fixing, let me know.

**Comment by frederikhors** [comment]
Ok. Thanks.
